### ISSUE TITLE
tl_layout translations

### ISSUE THREAD

**Issue by hamidabbaszadeh** [BugBuster1701/contao_grid_16_columns#16]
tl_layout translations do not show in layout in my installation (contao 3.4.0)!

**Comment by BugBuster1701** [comment]
Problem found, fixed as soon as possible.
Hint for me: 
```
wrong: ['grid-1120-16-pixel-responsive]['css']['0'] = ...
right: ['grid-1120-16-pixel-responsive.css']['0'] = ...
```

**Comment by BugBuster1701** [comment]
https://github.com/BugBuster1701/contao-toolbox/issues/2
